### ISSUE TITLE
coalgen_thinning_hetero

### ISSUE THREAD

**Issue by JuliaPalacios** [mdkarcher/phylodyn#8]
Hi @mdkarcher ,

I was looking at a code for the HMC paper where we used coalgen_thinning_hetero..()
there, we used traj_inv. Did you change it to be traj instead of the inverse? Will people who want to replicate the paper be able to do it right?

Thanks

**Comment by mdkarcher** [comment]
Yes, I tried to make it use traj rather than traj_inv since using traj_inv is not user-friendly, but I think I didn't do a good job of switching it over. I'm going to switch coalgen_thinning_hetero back to using traj_inv and write another function for users who aren't trying to use your code verbatim.
